// <auto-generated />
using System;
using Bookington.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bookington.Core.Migrations
{
    [DbContext(typeof(BookingtonDbContext))]
    [Migration("20230305060139_Bookington_DB_v1.6")]
    partial class BookingtonDBv16
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Bookington.Core.Entities.Account", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime")
                        .HasColumnName("create_at");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("FullName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("password");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("phone");

                    b.Property<string>("RefAvatar")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("ref_avatar");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("PK__accounts__3213E83FC82E5A90");

                    b.HasIndex("RefAvatar");

                    b.HasIndex("RoleId");

                    b.HasIndex(new[] { "Phone" }, "UQ__accounts__B43B145F4D261CD4")
                        .IsUnique();

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("Bookington.Core.Entities.AccountAvatar", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("id");

                    b.Property<string>("RefImage")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("ref_image");

                    b.HasKey("Id")
                        .HasName("PK__account___3213E83F3425597B");

                    b.ToTable("account_avatars", (string)null);
                });

            modelBuilder.Entity("Bookington.Core.Entities.AccountOtp", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime")
                        .HasColumnName("create_at");

                    b.Property<DateTime>("ExpireAt")
                        .HasColumnType("datetime")
                        .HasColumnName("expire_at");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("bit")
                        .HasColumnName("is_confirmed");

                    b.Property<string>("OtpCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("varchar(6)")
                        .HasColumnName("otp_code");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("phone");

                    b.Property<string>("RefAccount")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("ref_account");

                    b.HasKey("Id")
                        .HasName("PK__account___3213E83F4C00CC5F");

                    b.HasIndex("RefAccount");

                    b.ToTable("account_otps", (string)null);
                });

            modelBuilder.Entity("Bookington.Core.Entities.Ban", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("id");

                    b.Property<DateTime?>("BanUntil")
                        .HasColumnType("datetime")
                        .HasColumnName("ban_until");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime")
                        .HasColumnName("create_at");

                    b.Property<int>("Duration")
                        .HasColumnType("int")
                        .HasColumnName("duration");

                    b.Property<bool>("IsAccountBan")
                        .HasColumnType("bit")
                        .HasColumnName("is_account_ban");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsCourtBan")
                        .HasColumnType("bit")
                        .HasColumnName("is_court_ban");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("reason");

                    b.Property<string>("RefAccount")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("ref_account");

                    b.Property<string>("RefCourt")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("ref_court");

                    b.HasKey("Id")
                        .HasName("PK__bans__3213E83FF8A75CE5");

                    b.HasIndex("RefAccount");

                    b.HasIndex("RefCourt");

                    b.ToTable("bans", (string)null);
                });

            modelBuilder.Entity("Bookington.Core.Entities.Booking", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("id");

                    b.Property<DateTime>("BookAt")
                        .HasColumnType("datetime")
                        .HasColumnName("book_at");

                    b.Property<string>("BookBy")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("book_by");

                    b.Property<DateTime>("PlayDate")
                        .HasColumnType("date")
                        .HasColumnName("play_date");

                    b.Property<double>("Price")
                        .HasColumnType("float")
                        .HasColumnName("price");

                    b.Property<string>("RefOrder")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("ref_order");

                    b.Property<string>("RefSlot")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("ref_slot");

                    b.HasKey("Id")
                        .HasName("PK__bookings__3213E83F199C458A");

                    b.HasIndex("BookBy");

                    b.HasIndex("RefOrder");

                    b.HasIndex("RefSlot");

                    b.ToTable("bookings", (string)null);
                });

            modelBuilder.Entity("Bookington.Core.Entities.ChatMessage", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime")
                        .HasColumnName("create_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("RefChatroom")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("ref_chatroom");

                    b.Property<string>("RefOwner")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("ref_owner");

                    b.Property<string>("RefUser")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("ref_user");

                    b.Property<int>("SequenceOrder")
                        .HasColumnType("int")
                        .HasColumnName("sequence_order");

                    b.HasKey("Id")
                        .HasName("PK__chat_mes__3213E83F03BAEB0C");

                    b.HasIndex("RefChatroom");

                    b.HasIndex("RefOwner");

                    b.HasIndex("RefUser");

                    b.ToTable("chat_messages", (string)null);
                });

            modelBuilder.Entity("Bookington.Core.Entities.ChatRoom", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("RefOwner")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("ref_owner");

                    b.Property<string>("RefUser")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("ref_user");

                    b.HasKey("Id")
                        .HasName("PK__chat_roo__3213E83FBACFA368");

                    b.HasIndex("RefOwner");

                    b.HasIndex("RefUser");

                    b.ToTable("chat_rooms", (string)null);
                });

            modelBuilder.Entity("Bookington.Core.Entities.Comment", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("id");

                    b.Property<string>("CommentWriterId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("comment_writer_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime")
                        .HasColumnName("create_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<double>("Rating")
                        .HasColumnType("float")
                        .HasColumnName("rating");

                    b.Property<string>("RefCourt")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("ref_court");

                    b.HasKey("Id")
                        .HasName("PK__comments__3213E83FAB9D61B6");

                    b.HasIndex("CommentWriterId");

                    b.HasIndex("RefCourt");

                    b.ToTable("comments", (string)null);
                });

            modelBuilder.Entity("Bookington.Core.Entities.Court", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("address");

                    b.Property<TimeSpan>("CloseAt")
                        .HasColumnType("time")
                        .HasColumnName("close_at");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime")
                        .HasColumnName("create_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("description");

                    b.Property<string>("DistrictId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("district_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<TimeSpan>("OpenAt")
                        .HasColumnType("time")
                        .HasColumnName("open_at");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("owner_id");

                    b.HasKey("Id")
                        .HasName("PK__courts__3213E83F918EECEC");

                    b.HasIndex("DistrictId");

                    b.HasIndex("OwnerId");

                    b.ToTable("courts", (string)null);
                });

            modelBuilder.Entity("Bookington.Core.Entities.CourtImage", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("id");

                    b.Property<string>("CourtId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("court_id");

                    b.Property<string>("RefImage")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("ref_image");

                    b.HasKey("Id")
                        .HasName("PK__court_im__3213E83FD178DA00");

                    b.HasIndex("CourtId");

                    b.ToTable("court_images", (string)null);
                });

            modelBuilder.Entity("Bookington.Core.Entities.CourtReport", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("content");

                    b.Property<bool>("IsResponded")
                        .HasColumnType("bit")
                        .HasColumnName("is_responded");

                    b.Property<string>("RefCourt")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("ref_court");

                    b.Property<string>("RefResponse")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("ref_response");

                    b.Property<string>("ReporterId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("reporter_id");

                    b.HasKey("Id")
                        .HasName("PK__court_re__3213E83F78E36AD5");

                    b.HasIndex("RefCourt");

                    b.HasIndex("RefResponse");

                    b.HasIndex("ReporterId");

                    b.ToTable("court_reports", (string)null);
                });

            modelBuilder.Entity("Bookington.Core.Entities.CourtReportResponse", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("content");

                    b.HasKey("Id")
                        .HasName("PK__court_re__3213E83FEC7EEBB5");

                    b.ToTable("court_report_responses", (string)null);
                });

            modelBuilder.Entity("Bookington.Core.Entities.CourtType", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("content");

                    b.HasKey("Id")
                        .HasName("PK__court_ty__3213E83FC3A78D59");

                    b.ToTable("court_types", (string)null);
                });

            modelBuilder.Entity("Bookington.Core.Entities.District", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("id");

                    b.Property<string>("DistrictName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("district_name");

                    b.Property<string>("ProvinceId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("province_id");

                    b.HasKey("Id")
                        .HasName("PK__district__3213E83F11904467");

                    b.HasIndex("ProvinceId");

                    b.ToTable("districts", (string)null);
                });

            modelBuilder.Entity("Bookington.Core.Entities.LoginToken", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime")
                        .HasColumnName("create_at");

                    b.Property<DateTime>("ExpireAt")
                        .HasColumnType("datetime")
                        .HasColumnName("expire_at");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit")
                        .HasColumnName("is_revoked");

                    b.Property<string>("RefAccount")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("ref_account");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2048)")
                        .HasColumnName("refresh_token");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2048)")
                        .HasColumnName("token");

                    b.HasKey("Id")
                        .HasName("PK__login_to__3213E83F7DD2294A");

                    b.HasIndex("RefAccount");

                    b.ToTable("login_tokens", (string)null);
                });

            modelBuilder.Entity("Bookington.Core.Entities.Notification", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime")
                        .HasColumnName("create_at");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit")
                        .HasColumnName("is_read");

                    b.Property<string>("RefAccount")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("ref_account");

                    b.HasKey("Id")
                        .HasName("PK__notifica__3213E83FDDD6D746");

                    b.HasIndex("RefAccount");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("Bookington.Core.Entities.Order", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("id");

                    b.Property<bool>("IsCanceled")
                        .HasColumnType("bit")
                        .HasColumnName("is_canceled");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit")
                        .HasColumnName("is_paid");

                    b.Property<bool>("IsRefunded")
                        .HasColumnType("bit")
                        .HasColumnName("is_refunded");

                    b.Property<DateTime>("OrderAt")
                        .HasColumnType("datetime")
                        .HasColumnName("order_at");

                    b.Property<double>("OriginalPrice")
                        .HasColumnType("float")
                        .HasColumnName("original_price");

                    b.Property<double>("TotalPrice")
                        .HasColumnType("float")
                        .HasColumnName("total_price");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("transaction_id");

                    b.Property<string>("VoucherCode")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("voucher_code");

                    b.HasKey("Id")
                        .HasName("PK__orders__3213E83FCEC5BA3F");

                    b.HasIndex("TransactionId");

                    b.HasIndex("VoucherCode");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("Bookington.Core.Entities.Promotion", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("id");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime")
                        .HasColumnName("end_time");

                    b.Property<bool>("IsCourtPromotion")
                        .HasColumnType("bit")
                        .HasColumnName("is_court_promotion");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2048)")
                        .HasColumnName("link");

                    b.Property<int>("PromotionOrder")
                        .HasColumnType("int")
                        .HasColumnName("promotion_order");

                    b.Property<string>("RefCourt")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("ref_court");

                    b.Property<string>("RefImage")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("ref_image");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime")
                        .HasColumnName("start_time");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("PK__promotio__3213E83FA25F0716");

                    b.HasIndex("RefCourt");

                    b.ToTable("promotions", (string)null);
                });

            modelBuilder.Entity("Bookington.Core.Entities.Province", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("id");

                    b.Property<string>("ProvinceName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("province_name");

                    b.HasKey("Id")
                        .HasName("PK__province__3213E83F52E362D4");

                    b.ToTable("provinces", (string)null);
                });

            modelBuilder.Entity("Bookington.Core.Entities.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("id");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("role_name");

                    b.HasKey("Id")
                        .HasName("PK__roles__3213E83FCAA4D8CB");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("Bookington.Core.Entities.Slot", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("id");

                    b.Property<string>("DaysInSchedule")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("days_in_schedule");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time")
                        .HasColumnName("end_time");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<double>("Price")
                        .HasColumnType("float")
                        .HasColumnName("price");

                    b.Property<string>("RefSubCourt")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("ref_sub_court");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time")
                        .HasColumnName("start_time");

                    b.HasKey("Id")
                        .HasName("PK__slots__3213E83FBB3BE737");

                    b.HasIndex("RefSubCourt");

                    b.ToTable("slots", (string)null);
                });

            modelBuilder.Entity("Bookington.Core.Entities.SubCourt", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("id");

                    b.Property<string>("CourtTypeId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("court_type_id");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime")
                        .HasColumnName("create_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("ParentCourtId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("parent_court_id");

                    b.Property<int>("SlotDuration")
                        .HasColumnType("int")
                        .HasColumnName("slot_duration");

                    b.HasKey("Id")
                        .HasName("PK__sub_cour__3213E83FBEB5844F");

                    b.HasIndex("CourtTypeId");

                    b.HasIndex("ParentCourtId");

                    b.ToTable("sub_courts", (string)null);
                });

            modelBuilder.Entity("Bookington.Core.Entities.TransactionHistory", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("id");

                    b.Property<double>("Amount")
                        .HasColumnType("float")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime")
                        .HasColumnName("create_at");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("reason");

                    b.Property<string>("RefFrom")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("ref_from");

                    b.Property<string>("RefTo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("ref_to");

                    b.HasKey("Id")
                        .HasName("PK__transact__3213E83FF04F1EA8");

                    b.HasIndex("RefFrom");

                    b.HasIndex("RefTo");

                    b.ToTable("transaction_history", (string)null);
                });

            modelBuilder.Entity("Bookington.Core.Entities.UserBalance", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("id");

                    b.Property<double>("Balance")
                        .HasColumnType("float")
                        .HasColumnName("balance");

                    b.Property<string>("RefUser")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("ref_user");

                    b.HasKey("Id")
                        .HasName("PK__user_bal__3213E83FFB632C9E");

                    b.HasIndex("RefUser");

                    b.ToTable("user_balances", (string)null);
                });

            modelBuilder.Entity("Bookington.Core.Entities.UserReport", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("content");

                    b.Property<bool>("IsResponsed")
                        .HasColumnType("bit")
                        .HasColumnName("is_responsed");

                    b.Property<string>("RefResponse")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("ref_response");

                    b.Property<string>("RefUser")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("ref_user");

                    b.Property<string>("ReporterId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("reporter_id");

                    b.HasKey("Id")
                        .HasName("PK__user_rep__3213E83F5A965BED");

                    b.HasIndex("RefResponse");

                    b.HasIndex("RefUser");

                    b.HasIndex("ReporterId");

                    b.ToTable("user_reports", (string)null);
                });

            modelBuilder.Entity("Bookington.Core.Entities.UserReportResponse", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("content");

                    b.HasKey("Id")
                        .HasName("PK__user_rep__3213E83F8503C715");

                    b.ToTable("user_report_responses", (string)null);
                });

            modelBuilder.Entity("Bookington.Core.Entities.Voucher", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime")
                        .HasColumnName("create_at");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("create_by");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("description");

                    b.Property<double>("Discount")
                        .HasColumnType("float")
                        .HasColumnName("discount");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime")
                        .HasColumnName("end_date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<int>("MaxQuantity")
                        .HasColumnType("int")
                        .HasColumnName("max_quantity");

                    b.Property<string>("RefCourt")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("ref_court");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime")
                        .HasColumnName("start_date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("title");

                    b.Property<int>("Usages")
                        .HasColumnType("int")
                        .HasColumnName("usages");

                    b.Property<string>("VoucherCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("voucher_code");

                    b.HasKey("Id")
                        .HasName("PK__vouchers__3213E83F08758111");

                    b.HasIndex("CreateBy");

                    b.HasIndex("RefCourt");

                    b.HasIndex(new[] { "VoucherCode" }, "UQ__vouchers__21731069457448AB")
                        .IsUnique();

                    b.ToTable("vouchers", (string)null);
                });

            modelBuilder.Entity("Bookington.Core.Entities.Account", b =>
                {
                    b.HasOne("Bookington.Core.Entities.AccountAvatar", "RefAvatarNavigation")
                        .WithMany("Accounts")
                        .HasForeignKey("RefAvatar")
                        .IsRequired()
                        .HasConstraintName("FK__accounts__ref_av__2A4B4B5E");

                    b.HasOne("Bookington.Core.Entities.Role", "Role")
                        .WithMany("Accounts")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK__accounts__role_i__29572725");

                    b.Navigation("RefAvatarNavigation");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Bookington.Core.Entities.AccountOtp", b =>
                {
                    b.HasOne("Bookington.Core.Entities.Account", "RefAccountNavigation")
                        .WithMany("AccountOtps")
                        .HasForeignKey("RefAccount")
                        .IsRequired()
                        .HasConstraintName("FK__account_o__ref_a__2D27B809");

                    b.Navigation("RefAccountNavigation");
                });

            modelBuilder.Entity("Bookington.Core.Entities.Ban", b =>
                {
                    b.HasOne("Bookington.Core.Entities.Account", "RefAccountNavigation")
                        .WithMany("Bans")
                        .HasForeignKey("RefAccount")
                        .HasConstraintName("FK__bans__ref_accoun__7A672E12");

                    b.HasOne("Bookington.Core.Entities.Court", "RefCourtNavigation")
                        .WithMany("Bans")
                        .HasForeignKey("RefCourt")
                        .HasConstraintName("FK__bans__ref_court__7B5B524B");

                    b.Navigation("RefAccountNavigation");

                    b.Navigation("RefCourtNavigation");
                });

            modelBuilder.Entity("Bookington.Core.Entities.Booking", b =>
                {
                    b.HasOne("Bookington.Core.Entities.Account", "BookByNavigation")
                        .WithMany("Bookings")
                        .HasForeignKey("BookBy")
                        .IsRequired()
                        .HasConstraintName("FK__bookings__book_b__66603565");

                    b.HasOne("Bookington.Core.Entities.Order", "RefOrderNavigation")
                        .WithMany("Bookings")
                        .HasForeignKey("RefOrder")
                        .IsRequired()
                        .HasConstraintName("FK__bookings__ref_or__656C112C");

                    b.HasOne("Bookington.Core.Entities.Slot", "RefSlotNavigation")
                        .WithMany("Bookings")
                        .HasForeignKey("RefSlot")
                        .IsRequired()
                        .HasConstraintName("FK__bookings__ref_sl__6477ECF3");

                    b.Navigation("BookByNavigation");

                    b.Navigation("RefOrderNavigation");

                    b.Navigation("RefSlotNavigation");
                });

            modelBuilder.Entity("Bookington.Core.Entities.ChatMessage", b =>
                {
                    b.HasOne("Bookington.Core.Entities.ChatRoom", "RefChatroomNavigation")
                        .WithMany("ChatMessages")
                        .HasForeignKey("RefChatroom")
                        .IsRequired()
                        .HasConstraintName("FK__chat_mess__ref_c__6D0D32F4");

                    b.HasOne("Bookington.Core.Entities.Account", "RefOwnerNavigation")
                        .WithMany("ChatMessageRefOwnerNavigations")
                        .HasForeignKey("RefOwner")
                        .IsRequired()
                        .HasConstraintName("FK__chat_mess__ref_o__6E01572D");

                    b.HasOne("Bookington.Core.Entities.Account", "RefUserNavigation")
                        .WithMany("ChatMessageRefUserNavigations")
                        .HasForeignKey("RefUser")
                        .IsRequired()
                        .HasConstraintName("FK__chat_mess__ref_u__6EF57B66");

                    b.Navigation("RefChatroomNavigation");

                    b.Navigation("RefOwnerNavigation");

                    b.Navigation("RefUserNavigation");
                });

            modelBuilder.Entity("Bookington.Core.Entities.ChatRoom", b =>
                {
                    b.HasOne("Bookington.Core.Entities.Account", "RefOwnerNavigation")
                        .WithMany("ChatRoomRefOwnerNavigations")
                        .HasForeignKey("RefOwner")
                        .IsRequired()
                        .HasConstraintName("FK__chat_room__ref_o__693CA210");

                    b.HasOne("Bookington.Core.Entities.Account", "RefUserNavigation")
                        .WithMany("ChatRoomRefUserNavigations")
                        .HasForeignKey("RefUser")
                        .IsRequired()
                        .HasConstraintName("FK__chat_room__ref_u__6A30C649");

                    b.Navigation("RefOwnerNavigation");

                    b.Navigation("RefUserNavigation");
                });

            modelBuilder.Entity("Bookington.Core.Entities.Comment", b =>
                {
                    b.HasOne("Bookington.Core.Entities.Account", "CommentWriter")
                        .WithMany("Comments")
                        .HasForeignKey("CommentWriterId")
                        .IsRequired()
                        .HasConstraintName("FK__comments__commen__3E52440B");

                    b.HasOne("Bookington.Core.Entities.Court", "RefCourtNavigation")
                        .WithMany("Comments")
                        .HasForeignKey("RefCourt")
                        .IsRequired()
                        .HasConstraintName("FK__comments__ref_co__3F466844");

                    b.Navigation("CommentWriter");

                    b.Navigation("RefCourtNavigation");
                });

            modelBuilder.Entity("Bookington.Core.Entities.Court", b =>
                {
                    b.HasOne("Bookington.Core.Entities.District", "District")
                        .WithMany("Courts")
                        .HasForeignKey("DistrictId")
                        .IsRequired()
                        .HasConstraintName("FK__courts__district__38996AB5");

                    b.HasOne("Bookington.Core.Entities.Account", "Owner")
                        .WithMany("Courts")
                        .HasForeignKey("OwnerId")
                        .IsRequired()
                        .HasConstraintName("FK__courts__owner_id__37A5467C");

                    b.Navigation("District");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Bookington.Core.Entities.CourtImage", b =>
                {
                    b.HasOne("Bookington.Core.Entities.Court", "Court")
                        .WithMany("CourtImages")
                        .HasForeignKey("CourtId")
                        .IsRequired()
                        .HasConstraintName("FK__court_ima__court__3B75D760");

                    b.Navigation("Court");
                });

            modelBuilder.Entity("Bookington.Core.Entities.CourtReport", b =>
                {
                    b.HasOne("Bookington.Core.Entities.Court", "RefCourtNavigation")
                        .WithMany("CourtReports")
                        .HasForeignKey("RefCourt")
                        .IsRequired()
                        .HasConstraintName("FK__court_rep__ref_c__440B1D61");

                    b.HasOne("Bookington.Core.Entities.CourtReportResponse", "RefResponseNavigation")
                        .WithMany("CourtReports")
                        .HasForeignKey("RefResponse")
                        .HasConstraintName("FK__court_rep__ref_r__45F365D3");

                    b.HasOne("Bookington.Core.Entities.Account", "Reporter")
                        .WithMany("CourtReports")
                        .HasForeignKey("ReporterId")
                        .IsRequired()
                        .HasConstraintName("FK__court_rep__repor__44FF419A");

                    b.Navigation("RefCourtNavigation");

                    b.Navigation("RefResponseNavigation");

                    b.Navigation("Reporter");
                });

            modelBuilder.Entity("Bookington.Core.Entities.District", b =>
                {
                    b.HasOne("Bookington.Core.Entities.Province", "Province")
                        .WithMany("Districts")
                        .HasForeignKey("ProvinceId")
                        .IsRequired()
                        .HasConstraintName("FK__districts__provi__34C8D9D1");

                    b.Navigation("Province");
                });

            modelBuilder.Entity("Bookington.Core.Entities.LoginToken", b =>
                {
                    b.HasOne("Bookington.Core.Entities.Account", "RefAccountNavigation")
                        .WithMany("LoginTokens")
                        .HasForeignKey("RefAccount")
                        .IsRequired()
                        .HasConstraintName("FK__login_tok__ref_a__300424B4");

                    b.Navigation("RefAccountNavigation");
                });

            modelBuilder.Entity("Bookington.Core.Entities.Notification", b =>
                {
                    b.HasOne("Bookington.Core.Entities.Account", "RefAccountNavigation")
                        .WithMany("Notifications")
                        .HasForeignKey("RefAccount")
                        .IsRequired()
                        .HasConstraintName("FK__notificat__ref_a__74AE54BC");

                    b.Navigation("RefAccountNavigation");
                });

            modelBuilder.Entity("Bookington.Core.Entities.Order", b =>
                {
                    b.HasOne("Bookington.Core.Entities.TransactionHistory", "Transaction")
                        .WithMany("Orders")
                        .HasForeignKey("TransactionId")
                        .HasConstraintName("FK__orders__transact__60A75C0F");

                    b.HasOne("Bookington.Core.Entities.Voucher", "VoucherCodeNavigation")
                        .WithMany("Orders")
                        .HasForeignKey("VoucherCode")
                        .HasPrincipalKey("VoucherCode")
                        .HasConstraintName("FK__orders__voucher___619B8048");

                    b.Navigation("Transaction");

                    b.Navigation("VoucherCodeNavigation");
                });

            modelBuilder.Entity("Bookington.Core.Entities.Promotion", b =>
                {
                    b.HasOne("Bookington.Core.Entities.Court", "RefCourtNavigation")
                        .WithMany("Promotions")
                        .HasForeignKey("RefCourt")
                        .HasConstraintName("FK__promotion__ref_c__778AC167");

                    b.Navigation("RefCourtNavigation");
                });

            modelBuilder.Entity("Bookington.Core.Entities.Slot", b =>
                {
                    b.HasOne("Bookington.Core.Entities.SubCourt", "RefSubCourtNavigation")
                        .WithMany("Slots")
                        .HasForeignKey("RefSubCourt")
                        .IsRequired()
                        .HasConstraintName("FK__slots__ref_sub_c__5535A963");

                    b.Navigation("RefSubCourtNavigation");
                });

            modelBuilder.Entity("Bookington.Core.Entities.SubCourt", b =>
                {
                    b.HasOne("Bookington.Core.Entities.CourtType", "CourtType")
                        .WithMany("SubCourts")
                        .HasForeignKey("CourtTypeId")
                        .IsRequired()
                        .HasConstraintName("FK__sub_court__court__52593CB8");

                    b.HasOne("Bookington.Core.Entities.Court", "ParentCourt")
                        .WithMany("SubCourts")
                        .HasForeignKey("ParentCourtId")
                        .IsRequired()
                        .HasConstraintName("FK__sub_court__paren__5165187F");

                    b.Navigation("CourtType");

                    b.Navigation("ParentCourt");
                });

            modelBuilder.Entity("Bookington.Core.Entities.TransactionHistory", b =>
                {
                    b.HasOne("Bookington.Core.Entities.Account", "RefFromNavigation")
                        .WithMany("TransactionHistoryRefFromNavigations")
                        .HasForeignKey("RefFrom")
                        .IsRequired()
                        .HasConstraintName("FK__transacti__ref_f__5CD6CB2B");

                    b.HasOne("Bookington.Core.Entities.Account", "RefToNavigation")
                        .WithMany("TransactionHistoryRefToNavigations")
                        .HasForeignKey("RefTo")
                        .IsRequired()
                        .HasConstraintName("FK__transacti__ref_t__5DCAEF64");

                    b.Navigation("RefFromNavigation");

                    b.Navigation("RefToNavigation");
                });

            modelBuilder.Entity("Bookington.Core.Entities.UserBalance", b =>
                {
                    b.HasOne("Bookington.Core.Entities.Account", "RefUserNavigation")
                        .WithMany("UserBalances")
                        .HasForeignKey("RefUser")
                        .IsRequired()
                        .HasConstraintName("FK__user_bala__ref_u__71D1E811");

                    b.Navigation("RefUserNavigation");
                });

            modelBuilder.Entity("Bookington.Core.Entities.UserReport", b =>
                {
                    b.HasOne("Bookington.Core.Entities.UserReportResponse", "RefResponseNavigation")
                        .WithMany("UserReports")
                        .HasForeignKey("RefResponse")
                        .HasConstraintName("FK__user_repo__ref_r__4CA06362");

                    b.HasOne("Bookington.Core.Entities.Account", "RefUserNavigation")
                        .WithMany("UserReportRefUserNavigations")
                        .HasForeignKey("RefUser")
                        .IsRequired()
                        .HasConstraintName("FK__user_repo__ref_u__4AB81AF0");

                    b.HasOne("Bookington.Core.Entities.Account", "Reporter")
                        .WithMany("UserReportReporters")
                        .HasForeignKey("ReporterId")
                        .IsRequired()
                        .HasConstraintName("FK__user_repo__repor__4BAC3F29");

                    b.Navigation("RefResponseNavigation");

                    b.Navigation("RefUserNavigation");

                    b.Navigation("Reporter");
                });

            modelBuilder.Entity("Bookington.Core.Entities.Voucher", b =>
                {
                    b.HasOne("Bookington.Core.Entities.Account", "CreateByNavigation")
                        .WithMany("Vouchers")
                        .HasForeignKey("CreateBy")
                        .IsRequired()
                        .HasConstraintName("FK__vouchers__create__59063A47");

                    b.HasOne("Bookington.Core.Entities.Court", "RefCourtNavigation")
                        .WithMany("Vouchers")
                        .HasForeignKey("RefCourt")
                        .IsRequired()
                        .HasConstraintName("FK__vouchers__ref_co__59FA5E80");

                    b.Navigation("CreateByNavigation");

                    b.Navigation("RefCourtNavigation");
                });

            modelBuilder.Entity("Bookington.Core.Entities.Account", b =>
                {
                    b.Navigation("AccountOtps");

                    b.Navigation("Bans");

                    b.Navigation("Bookings");

                    b.Navigation("ChatMessageRefOwnerNavigations");

                    b.Navigation("ChatMessageRefUserNavigations");

                    b.Navigation("ChatRoomRefOwnerNavigations");

                    b.Navigation("ChatRoomRefUserNavigations");

                    b.Navigation("Comments");

                    b.Navigation("CourtReports");

                    b.Navigation("Courts");

                    b.Navigation("LoginTokens");

                    b.Navigation("Notifications");

                    b.Navigation("TransactionHistoryRefFromNavigations");

                    b.Navigation("TransactionHistoryRefToNavigations");

                    b.Navigation("UserBalances");

                    b.Navigation("UserReportRefUserNavigations");

                    b.Navigation("UserReportReporters");

                    b.Navigation("Vouchers");
                });

            modelBuilder.Entity("Bookington.Core.Entities.AccountAvatar", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("Bookington.Core.Entities.ChatRoom", b =>
                {
                    b.Navigation("ChatMessages");
                });

            modelBuilder.Entity("Bookington.Core.Entities.Court", b =>
                {
                    b.Navigation("Bans");

                    b.Navigation("Comments");

                    b.Navigation("CourtImages");

                    b.Navigation("CourtReports");

                    b.Navigation("Promotions");

                    b.Navigation("SubCourts");

                    b.Navigation("Vouchers");
                });

            modelBuilder.Entity("Bookington.Core.Entities.CourtReportResponse", b =>
                {
                    b.Navigation("CourtReports");
                });

            modelBuilder.Entity("Bookington.Core.Entities.CourtType", b =>
                {
                    b.Navigation("SubCourts");
                });

            modelBuilder.Entity("Bookington.Core.Entities.District", b =>
                {
                    b.Navigation("Courts");
                });

            modelBuilder.Entity("Bookington.Core.Entities.Order", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("Bookington.Core.Entities.Province", b =>
                {
                    b.Navigation("Districts");
                });

            modelBuilder.Entity("Bookington.Core.Entities.Role", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("Bookington.Core.Entities.Slot", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("Bookington.Core.Entities.SubCourt", b =>
                {
                    b.Navigation("Slots");
                });

            modelBuilder.Entity("Bookington.Core.Entities.TransactionHistory", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Bookington.Core.Entities.UserReportResponse", b =>
                {
                    b.Navigation("UserReports");
                });

            modelBuilder.Entity("Bookington.Core.Entities.Voucher", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
